-- Expand gym demo library: more muscle categories + free-weight / machine videos.

insert into public.gym_exercises (
  slug, name, muscle_group, equipment, difficulty, duration_seconds,
  demo_video_url, demo_thumbnail_url, cues
) values
  -- Legs / calves
  ('bulgarian-split-squat', 'Bulgarian split squat', 'legs', 'dumbbell', 'intermediate', 45,
   'https://www.youtube.com/embed/2C-uNgKwPLE', 'https://img.youtube.com/vi/2C-uNgKwPLE/hqdefault.jpg',
   'Rear foot elevated, front knee tracks over mid-foot, torso tall.'),
  ('dumbbell-step-up', 'Dumbbell step-up', 'legs', 'dumbbell', 'beginner', 40,
   'https://www.youtube.com/embed/dQqApCGd5Zc', 'https://img.youtube.com/vi/dQqApCGd5Zc/hqdefault.jpg',
   'Drive through the whole front foot; avoid pushing off the back toe.'),
  ('wall-sit', 'Wall sit', 'legs', 'bodyweight', 'beginner', 45,
   'https://www.youtube.com/embed/y-wV4VenusQ', 'https://img.youtube.com/vi/y-wV4VenusQ/hqdefault.jpg',
   'Thighs parallel, heels down, press low back gently into the wall.'),
  ('standing-calf-raise', 'Standing calf raise', 'calves', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/-M4-amot7hQ', 'https://img.youtube.com/vi/-M4-amot7hQ/hqdefault.jpg',
   'Rise onto big toes, pause, lower with control through a full stretch.'),
  ('seated-dumbbell-calf-raise', 'Seated dumbbell calf raise', 'calves', 'dumbbell', 'beginner', 35,
   'https://www.youtube.com/embed/JbyjNymZOt0', 'https://img.youtube.com/vi/JbyjNymZOt0/hqdefault.jpg',
   'Place dumbbells on knees, lift heels, and squeeze at the top.'),
  ('calf-raise-machine', 'Standing calf raise machine', 'calves', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/gwLzBJYoWlI', 'https://img.youtube.com/vi/gwLzBJYoWlI/hqdefault.jpg',
   'Shoulders under pads, full stretch at bottom, soft knees.'),
  ('seated-calf-machine', 'Seated calf raise machine', 'calves', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/JbyjNymZOt0', 'https://img.youtube.com/vi/JbyjNymZOt0/hqdefault.jpg',
   'Pad on lower thighs, lift through the balls of the feet.'),

  -- Glutes / posterior
  ('clamshell', 'Clamshell', 'glutes', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/KZzG-b_E9I0', 'https://img.youtube.com/vi/KZzG-b_E9I0/hqdefault.jpg',
   'Keep heels together, open top knee without rolling the pelvis back.'),
  ('donkey-kick', 'Donkey kick', 'glutes', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/SJ1Xuz9D-ZQ', 'https://img.youtube.com/vi/SJ1Xuz9D-ZQ/hqdefault.jpg',
   'Square hips, drive heel to ceiling, avoid arching the low back.'),
  ('fire-hydrant', 'Fire hydrant', 'glutes', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/Z21XsmmjzHk', 'https://img.youtube.com/vi/Z21XsmmjzHk/hqdefault.jpg',
   'Lift knee out to the side with a stable torso.'),
  ('cable-pull-through', 'Cable pull-through', 'glutes', 'cable', 'intermediate', 40,
   'https://www.youtube.com/embed/3XjJ2sD-f1g', 'https://img.youtube.com/vi/3XjJ2sD-f1g/hqdefault.jpg',
   'Hinge, keep arms straight, snap hips forward to stand tall.'),
  ('glute-kickback-machine', 'Glute kickback machine', 'glutes', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/SaS3i1kG9sU', 'https://img.youtube.com/vi/SaS3i1kG9sU/hqdefault.jpg',
   'Brace torso, kick back without twisting the hips.'),

  -- Chest / shoulders / traps
  ('incline-dumbbell-press', 'Incline dumbbell press', 'chest', 'dumbbell', 'intermediate', 45,
   'https://www.youtube.com/embed/8iPEnn-ltC8', 'https://img.youtube.com/vi/8iPEnn-ltC8/hqdefault.jpg',
   'Slight arch, wrists stacked, lower to outer chest.'),
  ('incline-push-up', 'Incline push-up', 'chest', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/cfZsML4CKcA', 'https://img.youtube.com/vi/cfZsML4CKcA/hqdefault.jpg',
   'Hands on a bench, body in one line, lower chest toward the edge.'),
  ('diamond-push-up', 'Diamond push-up', 'arms', 'bodyweight', 'intermediate', 35,
   'https://www.youtube.com/embed/J0DnG1_S92I', 'https://img.youtube.com/vi/J0DnG1_S92I/hqdefault.jpg',
   'Hands under sternum forming a diamond, elbows close to ribs.'),
  ('bench-dip', 'Bench dip', 'arms', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/0326dytygHc', 'https://img.youtube.com/vi/0326dytygHc/hqdefault.jpg',
   'Shoulders down, lower until elbows ~90°, press without shrugging.'),
  ('arnold-press', 'Arnold press', 'shoulders', 'dumbbell', 'intermediate', 40,
   'https://www.youtube.com/embed/6Z15_WdXmVw', 'https://img.youtube.com/vi/6Z15_WdXmVw/hqdefault.jpg',
   'Rotate palms as you press overhead; avoid excessive lumbar arch.'),
  ('pike-push-up', 'Pike push-up', 'shoulders', 'bodyweight', 'intermediate', 40,
   'https://www.youtube.com/embed/xuthWQetxbE', 'https://img.youtube.com/vi/xuthWQetxbE/hqdefault.jpg',
   'Hips high, lower head toward floor between hands.'),
  ('cable-lateral-raise', 'Cable lateral raise', 'shoulders', 'cable', 'beginner', 35,
   'https://www.youtube.com/embed/3VcKaXpzqRo', 'https://img.youtube.com/vi/3VcKaXpzqRo/hqdefault.jpg',
   'Lead with elbows, slight bend, stop at shoulder height.'),
  ('rear-delt-fly-machine', 'Rear delt fly machine', 'shoulders', 'machine', 'beginner', 35,
   'https://www.youtube.com/embed/9nhg_sZ7D3A', 'https://img.youtube.com/vi/9nhg_sZ7D3A/hqdefault.jpg',
   'Chest on pad, sweep arms back with soft elbows.'),
  ('dumbbell-shrug', 'Dumbbell shrug', 'traps', 'dumbbell', 'beginner', 30,
   'https://www.youtube.com/embed/cJRVVxmytaM', 'https://img.youtube.com/vi/cJRVVxmytaM/hqdefault.jpg',
   'Elevate shoulders straight up; avoid rolling forward.'),
  ('barbell-shrug', 'Barbell shrug', 'traps', 'dumbbell', 'beginner', 30,
   'https://www.youtube.com/embed/g6qbq4Lf1FI', 'https://img.youtube.com/vi/g6qbq4Lf1FI/hqdefault.jpg',
   'Stand tall, shrug up and hold briefly, lower slowly.'),
  ('upright-row', 'Dumbbell upright row', 'traps', 'dumbbell', 'intermediate', 35,
   'https://www.youtube.com/embed/um3VVzqunPU', 'https://img.youtube.com/vi/um3VVzqunPU/hqdefault.jpg',
   'Pull elbows high and wide; stop around chest height if shoulders feel pinched.'),

  -- Back / lower back
  ('chin-up', 'Chin-up', 'back', 'bodyweight', 'intermediate', 45,
   'https://www.youtube.com/embed/brhRXlOhsAM', 'https://img.youtube.com/vi/brhRXlOhsAM/hqdefault.jpg',
   'Underhand grip, pull chest to bar, control the descent.'),
  ('chest-supported-row', 'Chest-supported row machine', 'back', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/GZbfZ033f74', 'https://img.youtube.com/vi/GZbfZ033f74/hqdefault.jpg',
   'Chest glued to pad, pull handles to ribs, squeeze shoulder blades.'),
  ('superman-hold', 'Superman hold', 'lower_back', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/z6PJMBJjf04', 'https://img.youtube.com/vi/z6PJMBJjf04/hqdefault.jpg',
   'Lift arms and legs together, keep gaze down, breathe steadily.'),
  ('bird-dog', 'Bird dog', 'lower_back', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/wi_e0AD0TuQ', 'https://img.youtube.com/vi/wi_e0AD0TuQ/hqdefault.jpg',
   'Opposite arm and leg reach long; keep hips level.'),
  ('good-morning', 'Good morning', 'lower_back', 'dumbbell', 'intermediate', 40,
   'https://www.youtube.com/embed/5uIcXHzV7NM', 'https://img.youtube.com/vi/5uIcXHzV7NM/hqdefault.jpg',
   'Soft knees, hinge from hips with a flat back.'),
  ('back-extension-machine', 'Back extension machine', 'lower_back', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/ph3pddpKdq0', 'https://img.youtube.com/vi/ph3pddpKdq0/hqdefault.jpg',
   'Pad at hip crease, extend without hyperextending the neck.'),

  -- Core / full body
  ('russian-twist', 'Russian twist', 'core', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/wkD8rjkodUI', 'https://img.youtube.com/vi/wkD8rjkodUI/hqdefault.jpg',
   'Lean back slightly, rotate through the ribs, not just the arms.'),
  ('side-plank', 'Side plank', 'core', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/K2VljzCC16g', 'https://img.youtube.com/vi/K2VljzCC16g/hqdefault.jpg',
   'Stack feet or stagger, lift hips, keep a long neck.'),
  ('reverse-crunch', 'Reverse crunch', 'core', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/HyvFqW9CYvQ', 'https://img.youtube.com/vi/HyvFqW9CYvQ/hqdefault.jpg',
   'Curl pelvis toward ribs; avoid swinging with momentum.'),
  ('hanging-knee-raise', 'Hanging knee raise', 'core', 'bodyweight', 'intermediate', 40,
   'https://www.youtube.com/embed/RD_A-Z15ER4', 'https://img.youtube.com/vi/RD_A-Z15ER4/hqdefault.jpg',
   'Dead hang, raise knees without swinging wildly.'),
  ('cable-woodchop', 'Cable woodchop', 'core', 'cable', 'intermediate', 40,
   'https://www.youtube.com/embed/pAplQXk3Mks', 'https://img.youtube.com/vi/pAplQXk3Mks/hqdefault.jpg',
   'Rotate through the trunk, arms mostly straight, feet planted.'),
  ('cable-crunch', 'Cable crunch', 'core', 'cable', 'beginner', 35,
   'https://www.youtube.com/embed/ToJeyCrvVb0', 'https://img.youtube.com/vi/ToJeyCrvVb0/hqdefault.jpg',
   'Crunch ribs to pelvis; keep hips quiet.'),
  ('ab-crunch-machine', 'Ab crunch machine', 'core', 'machine', 'beginner', 35,
   'https://www.youtube.com/embed/Xyd_fa5zoUA', 'https://img.youtube.com/vi/Xyd_fa5zoUA/hqdefault.jpg',
   'Curl through the abs, exhale at the bottom of the crunch.'),
  ('farmer-carry', 'Farmer carry', 'full_body', 'dumbbell', 'beginner', 45,
   'https://www.youtube.com/embed/p5MNNofen7s', 'https://img.youtube.com/vi/p5MNNofen7s/hqdefault.jpg',
   'Tall posture, packed shoulders, short quick steps.'),
  ('kettlebell-swing', 'Kettlebell swing', 'full_body', 'dumbbell', 'intermediate', 40,
   'https://www.youtube.com/embed/YPisLRLbZmA', 'https://img.youtube.com/vi/YPisLRLbZmA/hqdefault.jpg',
   'Hinge hard, snap hips; bell floats to about chest height.'),
  ('thruster', 'Dumbbell thruster', 'full_body', 'dumbbell', 'intermediate', 45,
   'https://www.youtube.com/embed/L219ltLXVKw', 'https://img.youtube.com/vi/L219ltLXVKw/hqdefault.jpg',
   'Squat then drive into an overhead press in one fluid motion.'),

  -- Forearms
  ('wrist-curl', 'Wrist curl', 'forearms', 'dumbbell', 'beginner', 30,
   'https://www.youtube.com/embed/3Pz4yEo0xDY', 'https://img.youtube.com/vi/3Pz4yEo0xDY/hqdefault.jpg',
   'Forearms on thighs, curl wrists up through a full range.'),
  ('reverse-wrist-curl', 'Reverse wrist curl', 'forearms', 'dumbbell', 'beginner', 30,
   'https://www.youtube.com/embed/iQJDbWvb8s8', 'https://img.youtube.com/vi/iQJDbWvb8s8/hqdefault.jpg',
   'Palms down, lift knuckles; keep elbows glued to thighs.'),
  ('farmers-hold', 'Farmer hold', 'forearms', 'dumbbell', 'beginner', 40,
   'https://www.youtube.com/embed/p5MNNofen7s', 'https://img.youtube.com/vi/p5MNNofen7s/hqdefault.jpg',
   'Stand tall and grip hard without shrugging.'),

  -- Cardio extras
  ('box-jump', 'Box jump', 'cardio', 'bodyweight', 'intermediate', 35,
   'https://www.youtube.com/embed/NBYRt-kKOUo', 'https://img.youtube.com/vi/NBYRt-kKOUo/hqdefault.jpg',
   'Soft landing, full foot on box, step down between reps.'),
  ('high-knees', 'High knees', 'cardio', 'bodyweight', 'beginner', 30,
   'https://www.youtube.com/embed/8opcQdC-V-U', 'https://img.youtube.com/vi/8opcQdC-V-U/hqdefault.jpg',
   'Drive knees up, land light, keep torso upright.'),
  ('jump-rope', 'Jump rope', 'cardio', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/1BZM2Vre5ac', 'https://img.youtube.com/vi/1BZM2Vre5ac/hqdefault.jpg',
   'Relaxed shoulders, tiny hops, wrists turn the rope.'),
  ('rowing-machine', 'Rowing machine', 'cardio', 'cardio_machine', 'beginner', 60,
   'https://www.youtube.com/embed/FWP9hK0bFhQ', 'https://img.youtube.com/vi/FWP9hK0bFhQ/hqdefault.jpg',
   'Legs-drive then lean then arms; reverse on the recovery.'),
  ('stair-climber', 'Stair climber', 'cardio', 'cardio_machine', 'beginner', 60,
   'https://www.youtube.com/embed/aU4pyiB_oqI', 'https://img.youtube.com/vi/aU4pyiB_oqI/hqdefault.jpg',
   'Light hand support only, full foot on each step.'),
  ('ski-erg', 'SkiErg', 'cardio', 'cardio_machine', 'intermediate', 50,
   'https://www.youtube.com/embed/oTZX-F3gMxA', 'https://img.youtube.com/vi/oTZX-F3gMxA/hqdefault.jpg',
   'Hinge and pull handles down past hips; recover tall.'),

  -- Mobility extras
  ('worlds-greatest-stretch', 'World''s greatest stretch', 'mobility', 'bodyweight', 'beginner', 50,
   'https://www.youtube.com/embed/bh5m_vMVbXo', 'https://img.youtube.com/vi/bh5m_vMVbXo/hqdefault.jpg',
   'Lunge, rotate open through the ribs, keep back knee soft.'),
  ('thoracic-rotation', 'Open-book thoracic rotation', 'mobility', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/0e9J0oXQy8A', 'https://img.youtube.com/vi/0e9J0oXQy8A/hqdefault.jpg',
   'Knees stacked, open top arm toward the floor behind you.'),
  ('ankle-rocks', 'Ankle rocks', 'mobility', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/eP8yF5n3m0A', 'https://img.youtube.com/vi/eP8yF5n3m0A/hqdefault.jpg',
   'Knee tracks over mid-foot, heel stays down as far as possible.'),
  ('thread-the-needle', 'Thread the needle', 'mobility', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/2vFK0i0p3oQ', 'https://img.youtube.com/vi/2vFK0i0p3oQ/hqdefault.jpg',
   'Reach under the body, then open the same arm to the ceiling.'),

  -- Extra machines / cables
  ('preacher-curl-machine', 'Preacher curl machine', 'arms', 'machine', 'beginner', 35,
   'https://www.youtube.com/embed/fopTZGqxvoM', 'https://img.youtube.com/vi/fopTZGqxvoM/hqdefault.jpg',
   'Upper arms flat on pad, curl without swinging.'),
  ('tricep-extension-machine', 'Tricep extension machine', 'arms', 'machine', 'beginner', 35,
   'https://www.youtube.com/embed/2-LaADo_QT4', 'https://img.youtube.com/vi/2-LaADo_QT4/hqdefault.jpg',
   'Elbows fixed, extend fully, control the return.'),
  ('cable-kickback', 'Cable glute kickback', 'glutes', 'cable', 'beginner', 35,
   'https://www.youtube.com/embed/SEdqd1n0cvg', 'https://img.youtube.com/vi/SEdqd1n0cvg/hqdefault.jpg',
   'Ankle strapped, kick back with a slight knee bend.'),
  ('smith-reverse-lunge', 'Smith machine reverse lunge', 'legs', 'machine', 'intermediate', 45,
   'https://www.youtube.com/embed/L8fvypPrzzs', 'https://img.youtube.com/vi/L8fvypPrzzs/hqdefault.jpg',
   'Step back under control, front shin vertical, drive through front heel.')
on conflict (slug) do update set
  name = excluded.name,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  difficulty = excluded.difficulty,
  duration_seconds = excluded.duration_seconds,
  demo_video_url = excluded.demo_video_url,
  demo_thumbnail_url = excluded.demo_thumbnail_url,
  cues = excluded.cues;
